-- Movie Club round workflow foundation.
-- This migration is intentionally additive: it does not alter the existing
-- polls, bracket, movies, ratings, or members tables.

create table if not exists public.rounds (
  id bigint generated by default as identity primary key,
  month_key text not null,
  status text not null default 'DRAFT'
    check (status in ('DRAFT', 'ACTIVE', 'COMPLETE', 'CANCELLED')),
  mode text not null default 'scrambled'
    check (mode in ('scrambled', 'paired')),
  default_duration_hours integer not null default 24
    check (default_duration_hours > 0),
  timezone text not null default 'America/Los_Angeles',
  next_open_at timestamptz,
  created_by bigint references public.members(id) on delete set null,
  created_at timestamptz not null default now(),
  completed_at timestamptz,
  cancelled_at timestamptz,
  version integer not null default 1
);

create unique index if not exists rounds_one_active_month
  on public.rounds (month_key)
  where status in ('DRAFT', 'ACTIVE');

create table if not exists public.round_phases (
  id bigint generated by default as identity primary key,
  round_id bigint not null references public.rounds(id) on delete cascade,
  phase_type text not null check (phase_type in (
    'CATEGORY_SUBMISSIONS', 'CATEGORY_SPIN', 'MOVIE_SUBMISSIONS', 'BRACKET'
  )),
  status text not null default 'DRAFT'
    check (status in ('DRAFT', 'OPEN', 'CLOSED', 'CANCELLED')),
  opens_at timestamptz,
  closes_at timestamptz,
  closed_reason text check (closed_reason is null or closed_reason in (
    'EVERYONE_COMPLETE', 'TIMER', 'ADMIN', 'MINIMUM_NOT_MET'
  )),
  reopened_at timestamptz,
  reopened_by bigint references public.members(id) on delete set null,
  advanced_by bigint references public.members(id) on delete set null,
  advance_reason text,
  created_at timestamptz not null default now(),
  unique (round_id, phase_type)
);

create table if not exists public.category_submissions (
  id bigint generated by default as identity primary key,
  phase_id bigint not null references public.round_phases(id) on delete cascade,
  member_id bigint not null references public.members(id) on delete cascade,
  raw_text text not null check (char_length(trim(raw_text)) between 1 and 120),
  normalized_text text not null check (char_length(normalized_text) between 1 and 120),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (phase_id, member_id)
);

create index if not exists category_submissions_phase_idx
  on public.category_submissions (phase_id);

create table if not exists public.category_spins (
  id bigint generated by default as identity primary key,
  phase_id bigint not null references public.round_phases(id) on delete cascade,
  member_id bigint not null references public.members(id) on delete cascade,
  result_category text not null,
  result_weight integer not null check (result_weight > 0),
  random_receipt text not null,
  created_at timestamptz not null default now(),
  unique (phase_id, member_id)
);

create table if not exists public.movie_submissions (
  id bigint generated by default as identity primary key,
  phase_id bigint not null references public.round_phases(id) on delete cascade,
  member_id bigint not null references public.members(id) on delete cascade,
  slot smallint not null check (slot in (1, 2)),
  tmdb_id bigint,
  title text not null,
  year integer,
  poster text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (phase_id, member_id, slot)
);

create index if not exists movie_submissions_phase_idx
  on public.movie_submissions (phase_id);

create table if not exists public.bracket_entries (
  id bigint generated by default as identity primary key,
  round_id bigint not null references public.rounds(id) on delete cascade,
  entry_type text not null check (entry_type in ('MOVIE', 'PAIR')),
  source_member_id bigint references public.members(id) on delete set null,
  movie_a_id bigint,
  movie_b_id bigint,
  movie_a_tmdb_id bigint,
  movie_b_tmdb_id bigint,
  movie_a_title text,
  movie_b_title text,
  duplicate_score integer not null default 0 check (duplicate_score >= 0),
  bye_awarded boolean not null default false,
  seed integer,
  created_at timestamptz not null default now(),
  check (entry_type = 'MOVIE' or (movie_a_title is not null and movie_b_title is not null))
);

create index if not exists bracket_entries_round_idx
  on public.bracket_entries (round_id);

create table if not exists public.bracket_matchups (
  id bigint generated by default as identity primary key,
  round_id bigint not null references public.rounds(id) on delete cascade,
  bracket_round_number integer not null check (bracket_round_number >= 1),
  entry_a_id bigint references public.bracket_entries(id) on delete set null,
  entry_b_id bigint references public.bracket_entries(id) on delete set null,
  status text not null default 'OPEN'
    check (status in ('PENDING', 'OPEN', 'CLOSED', 'CANCELLED')),
  opens_at timestamptz,
  closes_at timestamptz,
  winner_entry_id bigint references public.bracket_entries(id) on delete set null,
  tie_resolved boolean not null default false,
  tie_resolution_note text,
  created_at timestamptz not null default now(),
  check (entry_a_id is not null or entry_b_id is not null)
);

create index if not exists bracket_matchups_round_idx
  on public.bracket_matchups (round_id, bracket_round_number);

create table if not exists public.bracket_votes (
  id bigint generated by default as identity primary key,
  matchup_id bigint not null references public.bracket_matchups(id) on delete cascade,
  member_id bigint not null references public.members(id) on delete cascade,
  entry_id bigint not null references public.bracket_entries(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (matchup_id, member_id)
);

create table if not exists public.round_events (
  id bigint generated by default as identity primary key,
  round_id bigint not null references public.rounds(id) on delete cascade,
  phase_id bigint references public.round_phases(id) on delete set null,
  event_type text not null,
  actor_member_id bigint references public.members(id) on delete set null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists round_events_round_idx
  on public.round_events (round_id, created_at);

create table if not exists public.home_notifications (
  id bigint generated by default as identity primary key,
  round_id bigint references public.rounds(id) on delete cascade,
  phase_id bigint references public.round_phases(id) on delete cascade,
  title text not null,
  body text not null,
  action_path text not null default '/poll',
  created_at timestamptz not null default now(),
  expires_at timestamptz
);

create index if not exists home_notifications_active_idx
  on public.home_notifications (created_at desc);

-- The new workflow is written through server-side functions. Do not expose
-- these tables to the anonymous browser client until those functions exist.
alter table public.rounds enable row level security;
alter table public.round_phases enable row level security;
alter table public.category_submissions enable row level security;
alter table public.category_spins enable row level security;
alter table public.movie_submissions enable row level security;
alter table public.bracket_entries enable row level security;
alter table public.bracket_matchups enable row level security;
alter table public.bracket_votes enable row level security;
alter table public.round_events enable row level security;
alter table public.home_notifications enable row level security;

-- updated_at is deliberately maintained by the application/server function
-- so edits create an auditable event rather than a hidden trigger mutation.
